import { page } from "vitest/browser"
import { describe, expect, it } from "vitest"
import { createCytoscapeGraphFrameResource } from "./6_graphRenderer.ts"

import { fitGraphCamera } from "../../src/2_graph/1_fitCamera.ts"
import type { GraphFrame } from "../../src/2_graph/0_frame.ts"

// The proof this file exists for: a real architecture diagram from this
// repository, rendered by the d2 binary, sealed into a GraphFrame, and drawn
// by the Cytoscape renderer in a real chromium. The svg is generated by
// `pnpm run proof:svg` before the suite runs.
describe("sealed architecture diagram proof", () => {
  it("draws the rendered artifact epic through the graph renderer", async () => {
    const archSvg = await (await fetch(new URL("./proof/arch.svg", import.meta.url).pathname)).text()
    const [, , width, height] = (/viewBox="([^"]+)"/.exec(archSvg)?.[1] ?? "")
      .split(/\s+/)
      .map(Number)
    expect(width).toBeGreaterThan(0)

    const frame: GraphFrame = {
      graph: {
        epic: {
          id: "epic",
          type: "node",
          layout: { mode: "sealed", bounds: { x: 0, y: 0, width, height }, geometryRevisionId: "epic:geometry:1" },
        },
      },
      geometry: {
        revisionId: "epic:1",
        boundsById: { epic: { x: 0, y: 0, width, height } },
        endpointAnchorById: { epic: { x: width / 2, y: height / 2 } },
        routesById: {},
        headerBoundsById: {},
      },
      camera: fitGraphCamera(
        {
          revisionId: "epic:1",
          boundsById: { epic: { x: 0, y: 0, width, height } },
          endpointAnchorById: { epic: { x: width / 2, y: height / 2 } },
          routesById: {},
          headerBoundsById: {},
        },
        { x: 0, y: 0, width: 1280, height: 800 },
        24,
      ),
      presentation: {
        stickyHeaders: [],
        hiddenIds: new Set(),
        focusedIds: new Set(),
        labelsById: {},
        sealedSvgArtifactsByRootId: {
          epic: {
            rootId: "epic",
            revisionId: "epic:svg:1",
            geometryRevisionId: "epic:geometry:1",
            svg: archSvg,
            sourceBounds: { x: 0, y: 0, width, height },
            fit: "contain",
          },
        },
      },
    }

    const host = document.createElement("div")
    host.setAttribute("style", "position:fixed;inset:0;background:#0b1220")
    document.body.appendChild(host)
    const resource = createCytoscapeGraphFrameResource(host)
    // The sealed root also owns a native hull node in Cytoscape; this proof is
    // about the sealed svg overlay, so the default-styled hull stays hidden.
    const cyContainer = host.querySelector("canvas")?.parentElement
    if (cyContainer) cyContainer.style.visibility = "hidden"
    resource.render(frame, { enterIds: ["epic"], updateIds: [], exitIds: [] })

    await expect
      .poll(() => (host.querySelector("svg") as SVGElement | null)?.querySelectorAll("g, path, rect, text").length ?? 0, {
        timeout: 5000,
      })
      .toBeGreaterThan(100)

    await page.screenshot({ path: "proof/arch-proof.png" })

    // The epic is 25k units wide, so the fitted shot is proof of render, not of
    // reading. The zoom camera targets the leftmost text cluster, measured out
    // of the mounted svg in source units, and follows the pan convention
    // fitGraphCamera uses: x and y are screen-space translation.
    const sealedSvg = host.querySelector<SVGElement>('[data-grapht-overlay="sealed-svg"] svg')
    expect(sealedSvg).not.toBeNull()
    const textNodes = [...(sealedSvg?.querySelectorAll("text") ?? [])]
    expect(textNodes.length).toBeGreaterThan(20)
    const boxes = textNodes
      .map(node => {
        const box = (node as SVGTextElement).getBBox()
        return { text: node.textContent?.trim() ?? "", x: box.x, y: box.y, width: box.width, height: box.height }
      })
      .filter(box => box.text.length > 0)
      .sort((left, right) => left.x + left.y - (right.x + right.y))
    const seed = boxes[0]
    const cluster = boxes.filter(box => Math.abs(box.x - seed.x) < 900 && Math.abs(box.y - seed.y) < 500)
    expect(cluster.length).toBeGreaterThan(3)
    const left = Math.max(Math.min(...cluster.map(box => box.x)) - 60, 0)
    const top = Math.max(Math.min(...cluster.map(box => box.y)) - 60, 0)
    const right = Math.min(Math.max(...cluster.map(box => box.x + box.width)) + 60, width)
    const bottom = Math.min(Math.max(...cluster.map(box => box.y + box.height)) + 60, height)

    // A 25k-unit svg element rasterizes into one downscaled texture and the
    // zoomed crop reads as fuzz. The zoom artifact carries the cluster window
    // in its root viewBox, so chromium rasterizes a viewport-sized element.
    const cropped = new DOMParser().parseFromString(archSvg, "image/svg+xml").documentElement
    cropped.setAttribute("viewBox", `${left} ${top} ${right - left} ${bottom - top}`)
    cropped.removeAttribute("width")
    cropped.removeAttribute("height")
    const zoomFrame: GraphFrame = {
      graph: frame.graph,
      geometry: {
        revisionId: "epic:zoom:1",
        boundsById: { epic: { x: 0, y: 0, width: 1280, height: 800 } },
        endpointAnchorById: { epic: { x: 640, y: 400 } },
        routesById: {},
        headerBoundsById: {},
      },
      camera: { x: 0, y: 0, scale: 1, viewport: { x: 0, y: 0, width: 1280, height: 800 } },
      presentation: {
        ...frame.presentation,
        sealedSvgArtifactsByRootId: {
          epic: {
            rootId: "epic",
            revisionId: "epic:svg:zoom:1",
            geometryRevisionId: "epic:zoom:1",
            svg: new XMLSerializer().serializeToString(cropped),
            sourceBounds: { x: left, y: top, width: right - left, height: bottom - top },
            fit: "contain",
          },
        },
      },
    }
    resource.render(zoomFrame, { enterIds: [], updateIds: ["epic"], exitIds: [] })

    const zoomView = host.querySelector<HTMLElement>('[data-grapht-overlay="sealed-svg"] [data-revision-id="epic:svg:zoom:1"]')
    expect(zoomView).not.toBeNull()
    const zoomSvg = zoomView?.querySelector("svg")
    const zoomRect = zoomSvg?.getBoundingClientRect()
    expect(zoomRect?.width).toBeGreaterThan(400)
    const zoomedText = zoomSvg?.querySelectorAll("text")[0] as SVGTextElement
    const textRect = zoomedText.getBoundingClientRect()
    expect(textRect.left).toBeGreaterThan(0)
    expect(textRect.right).toBeLessThan(1280)
    expect(textRect.height).toBeGreaterThan(6)

    await page.screenshot({ path: "proof/arch-zoom.png" })
    resource.unsubscribe()
    host.remove()
  })
})
