import { page } from "vitest/browser"
import { describe, expect, it } from "vitest"
import { createCytoscapeGraphFrameResource } from "./6_graphRenderer.ts"

import { fitGraphCamera } from "../../src/2_graph/1_fitCamera.ts"
import type { GraphFrame } from "../../src/2_graph/0_frame.ts"

// The proof this file exists for: a real architecture diagram from this
// repository, rendered by the d2 binary, sealed into a GraphFrame, and drawn
// by the Cytoscape renderer in a real chromium. The svg is generated by
// `pnpm run proof:svg` before the suite runs.
describe("sealed architecture diagram proof", () => {
  it("draws the rendered artifact epic through the graph renderer", async () => {
    const archSvg = await (await fetch(new URL("./proof/arch.svg", import.meta.url).pathname)).text()
    const [, , width, height] = (/viewBox="([^"]+)"/.exec(archSvg)?.[1] ?? "")
      .split(/\s+/)
      .map(Number)
    expect(width).toBeGreaterThan(0)

    const frame: GraphFrame = {
      graph: {
        epic: {
          id: "epic",
          type: "node",
          layout: { mode: "sealed", bounds: { x: 0, y: 0, width, height }, geometryRevisionId: "epic:geometry:1" },
        },
      },
      geometry: {
        revisionId: "epic:1",
        boundsById: { epic: { x: 0, y: 0, width, height } },
        endpointAnchorById: { epic: { x: width / 2, y: height / 2 } },
        routesById: {},
        headerBoundsById: {},
      },
      camera: fitGraphCamera(
        {
          revisionId: "epic:1",
          boundsById: { epic: { x: 0, y: 0, width, height } },
          endpointAnchorById: { epic: { x: width / 2, y: height / 2 } },
          routesById: {},
          headerBoundsById: {},
        },
        { x: 0, y: 0, width: 1280, height: 800 },
        24,
      ),
      presentation: {
        stickyHeaders: [],
        hiddenIds: new Set(),
        focusedIds: new Set(),
        labelsById: {},
        sealedSvgArtifactsByRootId: {
          epic: {
            rootId: "epic",
            revisionId: "epic:svg:1",
            geometryRevisionId: "epic:geometry:1",
            svg: archSvg,
            sourceBounds: { x: 0, y: 0, width, height },
            fit: "contain",
          },
        },
      },
    }

    const host = document.createElement("div")
    host.setAttribute("style", "position:fixed;inset:0;background:#0b1220")
    document.body.appendChild(host)
    const resource = createCytoscapeGraphFrameResource(host)
    resource.render(frame, { enterIds: ["epic"], updateIds: [], exitIds: [] })

    await expect
      .poll(() => (host.querySelector("svg") as SVGElement | null)?.querySelectorAll("g, path, rect, text").length ?? 0, {
        timeout: 5000,
      })
      .toBeGreaterThan(100)

    await page.screenshot({ path: "proof/arch-proof.png" })

    // The epic is 25k units wide, so the fitted shot is proof of render, not of
    // reading. A camera over the opening section at reading scale proves the
    // second half.
    resource.render(
      { ...frame, camera: { x: 950, y: 500, scale: 0.85, viewport: { x: 0, y: 0, width: 1280, height: 800 } } },
      { enterIds: [], updateIds: ["epic"], exitIds: [] },
    )
    await page.screenshot({ path: "proof/arch-zoom.png" })
    resource.unsubscribe()
    host.remove()
  })
})
