// @generated by @hafley66/json-rx
// DO NOT EDIT.

import { map, merge, scan, type Observable } from 'rxjs'
import type { UsageEvent, UsageSnapshot, UsageUpdate } from './0_models'

export function usageState(inputs: {
  snapshot: Observable<UsageSnapshot>
  update: Observable<UsageUpdate>
}): Observable<UsageSnapshot> {
  return merge(
    inputs.snapshot.pipe(map((value): UsageEvent => ({ type: 'snapshot', value }))),
    inputs.update.pipe(map((value): UsageEvent => ({ type: 'update', value }))),
  ).pipe(
    scan((state: UsageSnapshot, event: UsageEvent) => {
      switch (event.type) {
        case 'snapshot':
          return event.value
        case 'update':
          return { ...state, ...event.value }
      }
    }, {} as UsageSnapshot),
  )
}
