// @generated by @hafley66/json-rx
// DO NOT EDIT.

import { defer, finalize, map, merge, switchMap, timer, type Observable } from 'rxjs'
import type { RequestEvents, ResultId, DelayedRequest } from './0_models'

export type ResultIdMetrics = { active: number; cancellations: number }

export function latestResult(inputs: {
  request: Observable<DelayedRequest>
}, metrics: ResultIdMetrics): Observable<ResultId> {
  return merge(
    inputs.request.pipe(map((value): RequestEvents => ({ type: 'request', value }))),
  ).pipe(
    switchMap((event) => defer(() => {
      metrics.active += 1
      let emitted = false
      return timer(event.value.delayTicks).pipe(
        map(() => {
          emitted = true
          return event.value.id as ResultId
        }),
        finalize(() => {
          if (!emitted) metrics.cancellations += 1
          metrics.active -= 1
        }),
      )
    })),
  )
}
