import { expect, test } from "@playwright/test"

test("renders checked sequence SVGs and the generic graph through both production renderers", async ({ page }) => {
  await page.goto("/")
  await expect(page.getByRole("combobox", { name: "Renderer" })).toHaveValue("cytoscape")
  await expect(page.getByRole("combobox", { name: "Scenario" })).toHaveValue("mermaid")
  await expect(page.getByRole("button", { name: "Reset camera" })).toBeVisible()
  await expect(page.getByLabel("Current camera")).toContainText("camera:")
  await expect(page.locator("#graph")).toHaveAttribute("data-grapht-renderer", "cytoscape")
  await expect(page.locator("#graph canvas").first()).toBeVisible()
  await expect(page.locator("#graph")).not.toHaveAttribute("data-grapht-item-count", "1")
  const cytoscapeMovable = JSON.parse(await page.locator("#graph").getAttribute("data-grapht-movable-position") ?? "null") as { x: number; y: number }
  const cytoscapeGraph = await page.locator("#graph").boundingBox()
  if (cytoscapeGraph === null) throw new Error("Cytoscape graph has no bounds")
  await page.mouse.move(cytoscapeGraph.x + cytoscapeMovable.x, cytoscapeGraph.y + cytoscapeMovable.y)
  await page.mouse.down()
  await page.mouse.move(cytoscapeGraph.x + cytoscapeMovable.x + 30, cytoscapeGraph.y + cytoscapeMovable.y + 20, { steps: 4 })
  await page.mouse.up()
  await expect(page.locator("#graph")).not.toHaveAttribute("data-grapht-translations", "{}")
  await page.getByRole("button", { name: "Show sticky headers" }).click()
  await expect(page.locator('[data-grapht-overlay="sticky-headers"]')).toContainText("outer exchange")
  await expect(page.locator('[data-grapht-overlay="sticky-headers"]')).toContainText("nested review")
  await page.getByRole("button", { name: "Reset camera" }).click()
  await page.getByRole("combobox", { name: "Scenario" }).selectOption("d2")
  await expect(page.locator("#graph")).not.toHaveAttribute("data-grapht-item-count", "1")
  await page.getByRole("combobox", { name: "Renderer" }).selectOption("pixi")
  await expect(page.locator("#graph")).toHaveAttribute("data-grapht-renderer", "pixi")
  await expect(page.locator("#graph")).not.toHaveAttribute("data-grapht-interactive-binding-count", "0")
  await expect(page.locator("#graph canvas")).toHaveCount(1)
  await page.getByRole("combobox", { name: "Scenario" }).selectOption("generic")
  await expect(page.locator("#graph canvas")).toHaveCount(1)
  await expect(page.getByLabel("Focused IDs")).toContainText("focused:")
})
