// @generated by @hafley66/json-rx
// DO NOT EDIT.

import { Signal } from '@hafley66/signals'
import type { Observable } from 'rxjs'
import type { Value, Failure } from './0_models'

export type LifecycleState = { status: 'idle' | 'loading' | 'next' | 'error' | 'complete' | 'finalize'; data?: Value; error?: Failure; complete: boolean; loading: boolean; stale: boolean; updatedAt?: number; unsubscribed?: string }
export type LifecycleStateEvent = { kind: 'subscribe' } | { kind: 'loading' } | { kind: 'next'; data: Value; at: number } | { kind: 'error'; error: Failure } | { kind: 'complete' } | { kind: 'invalidate' } | { kind: 'unsubscribe'; reason: string } | { kind: 'finalize' }
export const initialLifecycleState: LifecycleState = { status: 'idle', complete: false, loading: false, stale: false }
export function reduceLifecycleState(state: LifecycleState, event: LifecycleStateEvent): LifecycleState {
  if (event.kind === 'subscribe') return { ...state, status: 'idle', complete: false, loading: false, unsubscribed: undefined }
  if (event.kind === 'loading') return { ...state, status: 'loading', loading: true }
  if (event.kind === 'next') return { ...state, status: 'next', data: event.data, error: undefined, loading: false, stale: false, updatedAt: event.at }
  if (event.kind === 'error') return { ...state, status: 'error', error: event.error, loading: false }
  if (event.kind === 'complete') return { ...state, status: 'complete', complete: true, loading: false }
  if (event.kind === 'invalidate') return { ...state, stale: true }
  if (event.kind === 'unsubscribe') return { ...state, loading: false, unsubscribed: event.reason }
  return { ...state, status: 'finalize', loading: false }
}
export function createLifecycleStateSignal(events: Observable<LifecycleStateEvent>) {
  const state = Signal(initialLifecycleState)
  let active = 1
  const subscription = events.subscribe((event) => state.$(reduceLifecycleState(state.$(), event)))
  return { state, metrics: { active: () => active }, dispose: () => { subscription.unsubscribe(); active = 0 } }
}
