// @generated by @hafley66/json-rx
// DO NOT EDIT.

use async_stream::stream;
use futures::{Stream, StreamExt};
use crate::models::{NumberEvent, Total, NumberInput};

pub fn running_total<S0>(mut value: S0) -> impl Stream<Item = Total>
where
    S0: Stream<Item = NumberInput> + Unpin,
{
    stream! {
        let mut state = 0 as Total;
        let mut value_done = false;
        loop {
            if value_done { break; }
            let event = tokio::select! {
                item = value.next(), if !value_done => match item {
                    Some(value) => NumberEvent::Value { value: value },
                    None => { value_done = true; continue; }
                },
            };
            let value = match event {
                NumberEvent::Value { value } => value * 2,
            };
            if !(value >= 4) { continue; }
            state = state + value;
            yield state;
        }
    }
}
