var PagesStrip=(function(e){Object.defineProperty(e,Symbol.toStringTag,{value:`Module`});var t=[{slug:`gothic`,title:`gothic`,blurb:`Procedural SVG notebooks: spec-derived bars, URL state per section, shuffle, draw-in.`,pkg:`@hafley66/gothic`,build:`pnpm --filter @hafley66/gothic build:single`,dist:`packages/gothic/dist`,hashRoutes:[`/arches`,`/architecture`,`/astrolabe`,`/border`,`/circles`,`/eye`,`/fma`,`/fractal`,`/frames`,`/guilloche`,`/icons`,`/slice`,`/tiles`,`/vello`]},{slug:`signal-grid`,title:`signal-grid`,blurb:`Relational data grid kernel: two ordered forests, five pure operators, RxJS intents, signal derivation.`,pkg:`@hafley66/signal-grid`,build:`pnpm --filter @hafley66/signal-grid ship`,dist:`packages/signal-grid/site/dist`},{slug:`signals`,title:`signals`,blurb:`RxJS-native reactive signals: one constructor, four forms, proxy-based nested access, no value and onChange pair.`,pkg:`@hafley66/signals`,build:`pnpm --filter @hafley66/signals ship`,dist:`packages/signals/site/dist`}];function n(e){var n;let r=e.split(`/`).filter(e=>e.length>0);return(n=t.find(e=>r.includes(e.slug)))==null?void 0:n.slug}function r(e){let t=n(e);if(t!==void 0){let n=`/${t}/`,r=e.indexOf(n);if(r>=0)return e.slice(0,r+1)}return e.endsWith(`/`)?e:e.replace(/[^/]*$/,``)}var i=`data-pages-strip`,a=`
.pages-strip {
  display: flex; flex-wrap: wrap; align-items: center; column-gap: 12px; row-gap: 2px;
  padding: 6px 14px; font: 13px/1.4 ui-monospace, Menlo, monospace;
  background: var(--panel-bg, light-dark(#fff, #161616));
  color: var(--muted, light-dark(#4a4a4a, #9aa0ad));
  border-bottom: 1px solid var(--line, light-dark(#ddd, #2a2a2a));
}
.pages-strip a { border-bottom: 2px solid transparent; padding: 1px 0; text-decoration: none; color: inherit }
.pages-strip a:hover { color: var(--fg, light-dark(#1a1a1a, #ddd)) }
.pages-strip a[aria-current] { border-color: var(--accent, #6fd7ad); color: var(--accent, #6fd7ad) }
.pages-strip-mark { opacity: .55; letter-spacing: .04em; text-transform: uppercase; font-size: 10px; margin-right: 2px }
`;function o(e){if(e.getElementById(`pages-strip-css`))return;let t=e.createElement(`style`);t.id=`pages-strip-css`,t.textContent=a,e.head.append(t)}function s(e){let t=e.querySelector(`[${i}]`);if(t instanceof HTMLElement)return t;let n=e.createElement(`div`);return n.setAttribute(i,``),e.body.prepend(n),n}function c(e,a){let o=e.ownerDocument,s=r(a),c=n(a),l=o.createElement(`nav`);l.className=`pages-strip`,l.setAttribute(`aria-label`,`packages`);let u=o.createElement(`span`);u.className=`pages-strip-mark`,u.textContent=`hafley-rxjs`,l.append(u);let d=o.createElement(`a`);d.href=s,d.dataset.tab=`hub`,d.textContent=`hub`,c===void 0&&d.setAttribute(`aria-current`,`page`),l.append(d);for(let e of t){let t=o.createElement(`a`);t.href=`${s}${e.slug}/`,t.dataset.tab=e.slug,t.title=e.blurb,t.textContent=e.title,e.slug===c&&t.setAttribute(`aria-current`,`page`),l.append(t)}e.replaceChildren(l),e.setAttribute(i,c==null?`hub`:c);let f=l.getBoundingClientRect().height;f>0&&o.documentElement.style.setProperty(`--pages-strip-h`,`${Math.round(f)}px`)}function l(){typeof document>`u`||(o(document),c(s(document),location.pathname))}return document.readyState===`loading`?document.addEventListener(`DOMContentLoaded`,l,{once:!0}):l(),e.renderStrip=c,e})({});