var PagesStrip=(function(e){Object.defineProperty(e,Symbol.toStringTag,{value:`Module`});var t=[{slug:`gothic`,title:`gothic`,blurb:`Procedural SVG notebooks: spec-derived bars, URL state per section, shuffle, draw-in.`,pkg:`@hafley66/gothic`,build:`pnpm --filter @hafley66/gothic build:single`,dist:`packages/gothic/dist`,hashRoutes:[`/arches`,`/architecture`,`/astrolabe`,`/border`,`/circles`,`/eye`,`/fma`,`/fractal`,`/frames`,`/guilloche`,`/icons`,`/kh`,`/slice`,`/tiles`,`/vello`]},{slug:`signal-grid`,title:`signal-grid`,blurb:`Relational data grid kernel: two ordered forests, five pure operators, RxJS intents, signal derivation.`,pkg:`@hafley66/signal-grid`,build:`pnpm --filter @hafley66/signal-grid ship`,dist:`packages/signal-grid/site/dist`},{slug:`signals`,title:`signals`,blurb:`RxJS-native reactive signals: one constructor, four forms, proxy-based nested access, no value and onChange pair.`,pkg:`@hafley66/signals`,build:`pnpm --filter @hafley66/signals ship`,dist:`packages/signals/site/dist`}];function n(e){var n;let r=e.split(`/`).filter(e=>e.length>0);return(n=t.find(e=>r.includes(e.slug)))==null?void 0:n.slug}function r(e){let t=n(e);if(t!==void 0){let n=`/${t}/`,r=e.indexOf(n);if(r>=0)return e.slice(0,r+1)}return e.endsWith(`/`)?e:e.replace(/[^/]*$/,``)}var i=`data-pages-strip`,a=`
.pages-strip {
  display: flex; flex-wrap: wrap; align-items: center; column-gap: 12px; row-gap: 2px;
  padding: 6px 14px; font: 13px/1.4 ui-monospace, Menlo, monospace;
  background: var(--panel-bg, var(--vp-c-bg-alt, light-dark(#fff, #161616)));
  color: var(--muted, var(--vp-c-text-2, light-dark(#4a4a4a, #9aa0ad)));
  border-bottom: 1px solid var(--line, var(--vp-c-divider, light-dark(#ddd, #2a2a2a)));
}
.pages-strip a { border-bottom: 2px solid transparent; padding: 1px 0; text-decoration: none; color: inherit }
.pages-strip a:hover { color: var(--fg, var(--vp-c-text-1, light-dark(#1a1a1a, #ddd))) }
.pages-strip a[aria-current] { border-color: var(--accent, var(--vp-c-brand-1, #6fd7ad)); color: var(--accent, var(--vp-c-brand-1, #6fd7ad)) }
.pages-strip-mark { opacity: .55; letter-spacing: .04em; text-transform: uppercase; font-size: 10px; margin-right: 2px }
.pages-strip-fixed .pages-strip { position: fixed; inset-inline: 0; top: 0; z-index: 60 }
`,o=e=>e.defaultView!==null&&e.defaultView.getComputedStyle(e.documentElement).getPropertyValue(`--vp-nav-height`).trim()!==``;function s(e){if(e.getElementById(`pages-strip-css`))return;let t=e.createElement(`style`);t.id=`pages-strip-css`,t.textContent=a,e.head.append(t)}function c(e){let t=e.querySelector(`[${i}]`);if(t instanceof HTMLElement)return t;let n=e.createElement(`div`);return n.setAttribute(i,``),e.body.prepend(n),n}function l(e,a){let s=e.ownerDocument,c=r(a),l=n(a),u=s.createElement(`nav`);u.className=`pages-strip`,u.setAttribute(`aria-label`,`packages`);let d=s.createElement(`span`);d.className=`pages-strip-mark`,d.textContent=`hafley-rxjs`,u.append(d);let f=s.createElement(`a`);f.href=c,f.dataset.tab=`hub`,f.textContent=`hub`,l===void 0&&f.setAttribute(`aria-current`,`page`),u.append(f);for(let e of t){let t=s.createElement(`a`);t.href=`${c}${e.slug}/`,t.dataset.tab=e.slug,t.title=e.blurb,t.textContent=e.title,e.slug===l&&t.setAttribute(`aria-current`,`page`),u.append(t)}e.replaceChildren(u),e.setAttribute(i,l==null?`hub`:l);let p=o(s);e.classList.toggle(`pages-strip-fixed`,p);let m=()=>{let e=Math.round(u.getBoundingClientRect().height);e<=0||(s.documentElement.style.setProperty(`--pages-strip-h`,`${e}px`),p&&s.documentElement.style.setProperty(`--vp-layout-top-height`,`${e}px`))};m(),typeof ResizeObserver<`u`&&new ResizeObserver(m).observe(u)}function u(){typeof document>`u`||(s(document),l(c(document),location.pathname))}return document.readyState===`loading`?document.addEventListener(`DOMContentLoaded`,u,{once:!0}):u(),e.renderStrip=l,e})({});