// @generated by @hafley66/json-rx
// DO NOT EDIT.

import { map, merge, scan, filter, type Observable } from 'rxjs'
import type { NumberEvent, Total, NumberInput } from './0_models'

export function runningTotal(inputs: {
  value: Observable<NumberInput>
}): Observable<Total> {
  return merge(
    inputs.value.pipe(map((value): NumberEvent => ({ type: 'value', value }))),
  ).pipe(
    map((event: NumberEvent) => event.value * 2),
    filter((value) => value >= 4),
    scan((state: Total, value) => state + value, 0 as Total),
  )
}
