import { describe, expect, it } from "vitest";
import { d2ThemeId, diagramPalette, mermaidTheme } from "./0_diagramTheme.js";

describe("diagram themes", () => {
  it("keeps text, surfaces, and renderer selections paired by mode", () => {
    expect({
      light: {
        palette: diagramPalette.light,
        mermaid: mermaidTheme(false),
        d2: d2ThemeId(false),
      },
      dark: {
        palette: diagramPalette.dark,
        mermaid: mermaidTheme(true),
        d2: d2ThemeId(true),
      },
    }).toMatchInlineSnapshot(`
      {
        "dark": {
          "d2": 200,
          "mermaid": {
            "theme": "base",
            "themeVariables": {
              "activationBkgColor": "#172554",
              "activationBorderColor": "#94a3b8",
              "actorBkg": "#1e293b",
              "actorBorder": "#94a3b8",
              "actorLineColor": "#cbd5e1",
              "actorTextColor": "#f8fafc",
              "altBackground": "#172554",
              "attributeBackgroundColorEven": "#172554",
              "attributeBackgroundColorOdd": "#1e293b",
              "background": "#0f172a",
              "classText": "#f8fafc",
              "clusterBkg": "#0f172a",
              "clusterBorder": "#94a3b8",
              "edgeLabelBackground": "#0f172a",
              "labelBoxBkgColor": "#172554",
              "labelBoxBorderColor": "#94a3b8",
              "labelColor": "#f8fafc",
              "labelTextColor": "#f8fafc",
              "lineColor": "#cbd5e1",
              "loopTextColor": "#f8fafc",
              "mainBkg": "#1e293b",
              "nodeBorder": "#94a3b8",
              "noteBkgColor": "#3f1d2e",
              "noteBorderColor": "#94a3b8",
              "noteTextColor": "#f8fafc",
              "primaryBorderColor": "#94a3b8",
              "primaryColor": "#1e293b",
              "primaryTextColor": "#f8fafc",
              "secondaryBorderColor": "#94a3b8",
              "secondaryColor": "#172554",
              "secondaryTextColor": "#f8fafc",
              "sequenceNumberColor": "#0f172a",
              "signalColor": "#cbd5e1",
              "signalTextColor": "#f8fafc",
              "tertiaryBorderColor": "#94a3b8",
              "tertiaryColor": "#3f1d2e",
              "tertiaryTextColor": "#f8fafc",
              "textColor": "#f8fafc",
            },
          },
          "palette": {
            "background": "#0f172a",
            "border": "#94a3b8",
            "line": "#cbd5e1",
            "surface": "#1e293b",
            "surfaceAlt": "#172554",
            "surfaceMuted": "#3f1d2e",
            "text": "#f8fafc",
          },
        },
        "light": {
          "d2": 8,
          "mermaid": {
            "theme": "base",
            "themeVariables": {
              "activationBkgColor": "#dcfce7",
              "activationBorderColor": "#475569",
              "actorBkg": "#e0e7ff",
              "actorBorder": "#475569",
              "actorLineColor": "#334155",
              "actorTextColor": "#111827",
              "altBackground": "#dcfce7",
              "attributeBackgroundColorEven": "#dcfce7",
              "attributeBackgroundColorOdd": "#e0e7ff",
              "background": "#f8fafc",
              "classText": "#111827",
              "clusterBkg": "#f8fafc",
              "clusterBorder": "#475569",
              "edgeLabelBackground": "#f8fafc",
              "labelBoxBkgColor": "#dcfce7",
              "labelBoxBorderColor": "#475569",
              "labelColor": "#111827",
              "labelTextColor": "#111827",
              "lineColor": "#334155",
              "loopTextColor": "#111827",
              "mainBkg": "#e0e7ff",
              "nodeBorder": "#475569",
              "noteBkgColor": "#fef3c7",
              "noteBorderColor": "#475569",
              "noteTextColor": "#111827",
              "primaryBorderColor": "#475569",
              "primaryColor": "#e0e7ff",
              "primaryTextColor": "#111827",
              "secondaryBorderColor": "#475569",
              "secondaryColor": "#dcfce7",
              "secondaryTextColor": "#111827",
              "sequenceNumberColor": "#f8fafc",
              "signalColor": "#334155",
              "signalTextColor": "#111827",
              "tertiaryBorderColor": "#475569",
              "tertiaryColor": "#fef3c7",
              "tertiaryTextColor": "#111827",
              "textColor": "#111827",
            },
          },
          "palette": {
            "background": "#f8fafc",
            "border": "#475569",
            "line": "#334155",
            "surface": "#e0e7ff",
            "surfaceAlt": "#dcfce7",
            "surfaceMuted": "#fef3c7",
            "text": "#111827",
          },
        },
      }
    `);
  });
});
