export { type FsColumnsOptions, type FsRow, FsTree, type FsTreeProps, fsColumns } from "./components/FsTree.js"
export { NavRail, type NavRailProps } from "./components/NavRail.js"
export { type Anchor, NavTabs, type NavTabsProps, type Tab } from "./components/NavTabs.js"
export { PivotStack, pivotColumns, type PivotStackProps } from "./components/PivotStack.js"
export { GearButton, PopoverPanel } from "./components/Popover.js"
export { PresetsMenu, type PresetsMenuProps } from "./components/PresetsMenu.js"
export { ReportShell, type ReportShellProps, type ReportTracks } from "./components/ReportShell.js"
export { PlainSection, Section, type SectionCtx, type SectionDef, type SectionProps } from "./components/Section.js"
export { inputId, SpecPanel, type SpecPanelProps, type Val } from "./components/SpecPanel.js"
export { StateCombo } from "./components/StateCombo.js"
export { SubTable } from "./components/SubTable.js"
export { Truncated } from "./components/Truncated.js"
export { usePivotEffect } from "./components/usePivotEffect.js"
export { type ThemePrefs, useTheme } from "./components/useTheme.js"
// layout/gutter/sizing moved to @hafley66/xdom (vanilla, no react peer); re-exported so this API is unchanged
export { type GutterOptions, gutter, type Layout, layout, type Track } from "@hafley66/xdom"
export { formatBytes } from "./lib/bytes.js"
export { stagger, useAnchor, useDrawIn, useResizeVar, useSideWidth, wideScreen } from "./lib/hooks.js"
export { enableTips } from "./lib/tips.js"
export { createNavCollapse, NAV_RAIL_PX, type NavCollapse } from "./lib/navCollapse.js"
export { decodePivotStack, encodePivotStack, pivotStackSignal, popPivotsTo, pushPivot } from "./lib/pivotStack.js"
export { formatAge, formatDuration } from "./lib/time.js"
export { createSizingStore, type Sizing, type SizingStore } from "@hafley66/xdom"
// marbler-bound pieces (EventsPanel, syncMarbler) live on the './marbler' subpath so pixi stays optional
export * from "./spec/0_spec.js"
export * from "./spec/1_url.js"
export * from "./spec/2_store.js"
export * from "./spec/3_sections.js"
export type { NavRow, PivotEntry } from "./types.js"
