export { layout, gutter, type Layout, type Track, type GutterOptions } from './layout'
export { createSizingStore, type Sizing, type SizingStore } from './sizing'
export { formatAge, formatDuration } from './lib/time'
export { createNavCollapse, NAV_RAIL_PX, type NavCollapse } from './lib/navCollapse'
export type { NavRow, PivotEntry } from './types'
export { Truncated } from './components/Truncated'
export { SubTable } from './components/SubTable'
export { GearButton, PopoverPanel } from './components/Popover'
export { PresetsMenu, type PresetsMenuProps } from './components/PresetsMenu'
export { PivotStack, type PivotStackProps } from './components/PivotStack'
// @deprecated: use @hafley66/grid's TreeTable for new nav trees; see README's "NavGrid is deprecated".
export { NavGrid, type NavGridProps } from './components/NavGrid'
export { NavRail, type NavRailProps } from './components/NavRail'
export { EventsPanel, defaultEventDetail, type EventsPanelProps } from './components/EventsPanel'
export { pivotStackSignal, pushPivot, popPivotsTo, encodePivotStack, decodePivotStack } from './lib/pivotStack'
export { usePivotEffect } from './components/usePivotEffect'
export { useTheme, type ThemePrefs } from './components/useTheme'
export { syncMarbler } from './lib/marblerSync'
export { ReportShell, type ReportShellProps, type ReportTracks } from './components/ReportShell'
