export { layout, gutter, type Layout, type Track, type GutterOptions } from './layout'
export { createSizingStore, type Sizing, type SizingStore } from './sizing'
export { formatAge, formatDuration } from './lib/time'
export { createNavCollapse, NAV_RAIL_PX, type NavCollapse } from './lib/navCollapse'
export type { NavRow, PivotEntry } from './types'
export { Truncated } from './components/Truncated'
export { SubTable } from './components/SubTable'
export { GearButton, PopoverPanel } from './components/Popover'
export { PresetsMenu, type PresetsMenuProps } from './components/PresetsMenu'
export { PivotStack, type PivotStackProps } from './components/PivotStack'
// @deprecated: use @hafley66/grid's TreeTable for new nav trees; see README's "NavGrid is deprecated".
export { NavGrid, type NavGridProps } from './components/NavGrid'
export { NavRail, type NavRailProps } from './components/NavRail'
export { pivotStackSignal, pushPivot, popPivotsTo, encodePivotStack, decodePivotStack } from './lib/pivotStack'
export { usePivotEffect } from './components/usePivotEffect'
export { useTheme, type ThemePrefs } from './components/useTheme'
export { ReportShell, type ReportShellProps, type ReportTracks } from './components/ReportShell'
// marbler-bound pieces (EventsPanel, syncMarbler) live on the './marbler' subpath so pixi stays optional
export * from './spec/0_spec'
export * from './spec/1_url'
export * from './spec/2_store'
export * from './spec/3_sections'
export { stagger, useDrawIn, useResizeVar, useAnchor } from './lib/hooks'
export { NavTabs, type NavTabsProps, type Tab, type Anchor } from './components/NavTabs'
export { Drawer, useDrawerBody, DRAWER_BODY_ID, type DrawerProps } from './components/Drawer'
export { SpecPanel, inputId, type SpecPanelProps } from './components/SpecPanel'
export { StateCombo } from './components/StateCombo'
export { Section, PlainSection, type SectionDef, type SectionCtx, type SectionProps } from './components/Section'
export { formatBytes } from './lib/bytes'
export { FsTree, fsColumns, type FsRow, type FsTreeProps, type FsColumnsOptions } from './components/FsTree'
