export {
  EDGE_COLOR,
  EDGE_THICKNESS,
  NODE_COLOR,
  NODE_RADIUS,
  NODE_SEGMENTS,
  ThreeProjection,
  type ActualBackend,
  type CameraState,
  type PixelReadback,
  type RendererMode,
  type Representation,
  type ThreeProjectionInfo,
  type ThreeProjectionOptions,
  type ThreeRenderer,
} from "./2_projection.js"
