// @generated by @hafley66/json-rx
// DO NOT EDIT.

use async_stream::stream;
use futures::{future, Stream, StreamExt};
use std::{sync::{Arc, atomic::Ordering}, time::Duration};
use crate::models::{ResultId, DelayedRequest, ResultIdMetrics};

struct ResultIdActiveTask(Arc<ResultIdMetrics>);

impl Drop for ResultIdActiveTask {
    fn drop(&mut self) {
        self.0.active.fetch_sub(1, Ordering::SeqCst);
    }
}

pub fn latest_result<S0>(mut request: S0, metrics: Arc<ResultIdMetrics>) -> impl Stream<Item = ResultId>
where
    S0: Stream<Item = DelayedRequest> + Unpin,
{
    stream! {
        let mut request_done = false;
        let mut active: Option<tokio::task::JoinHandle<ResultId>> = None;
        loop {
            if request_done && active.is_none() { break; }
            tokio::select! {
                item = request.next(), if !request_done => match item {
                    Some(value) => {
                        if let Some(task) = active.take() {
                            metrics.cancellations.fetch_add(1, Ordering::SeqCst);
                            task.abort();
                            let _ = task.await;
                        }
                        let delay = value.delayTicks;
                        let output = value.id;
                        let task_metrics = metrics.clone();
                        active = Some(tokio::spawn(async move {
                            task_metrics.active.fetch_add(1, Ordering::SeqCst);
                            let _active = ResultIdActiveTask(task_metrics);
                            tokio::time::sleep(Duration::from_millis(delay as u64)).await;
                            output
                        }));
                    }
                    None => request_done = true,
                },
                result = async {
                    match active.as_mut() {
                        Some(task) => task.await,
                        None => future::pending().await,
                    }
                }, if active.is_some() => {
                    active = None;
                    if let Ok(output) = result { yield output; }
                },
            }
        }
    }
}
