// Publish the canonical plans with browser links; implementation status stays in the source plan.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const pkg = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const workspace = resolve(pkg, "../..")
const directory = "plans/2026-09-13-anim-to-grapht"
const files = readdirSync(resolve(workspace, directory)).filter(file => /^\d+_.*\.md$/.test(file)).sort()
const slugOf = file => `plan-${file.replace(/^\d+_/, "").replace(/\.md$/, "")}`
const localRoots = [
  ["/Users/chrishafley/projects/hafley-rxjs/", "https://github.com/hafley66/hafley-rxjs/blob/main/"],
  ["/Users/chrishafley/projects/anim/", "https://github.com/hafley66/anim/blob/main/"],
]

for (const file of files) {
  const source = `${directory}/${file}`
  let body = readFileSync(resolve(workspace, source), "utf8")
  body = body.replace(/\]\(([^)]+)\)/g, (whole, target) => {
    if (files.includes(target)) return `](./${slugOf(target)})`
    for (const [root, url] of localRoots) {
      if (!target.startsWith(root)) continue
      const relative = target.slice(root.length)
      if (root.endsWith("hafley-rxjs/") && !existsSync(resolve(workspace, relative))) {
        throw new Error(`${source}: source link does not exist: ${relative}`)
      }
      return `](${url}${relative})`
    }
    if (target.startsWith("/")) throw new Error(`${source}: unpublished local link ${target}`)
    return whole
  })
  const headingEnd = body.indexOf("\n")
  body = `${body.slice(0, headingEnd)}\n\n::: warning Proposed work\nThis page describes a plan. Its signatures are sketches, and its acceptance checks have not established a shipped feature.\n:::\n\n[Canonical plan](https://github.com/hafley66/hafley-rxjs/blob/main/${source}) · [Feature status](./roadmap)\n${body.slice(headingEnd)}`
  writeFileSync(resolve(pkg, `docs/${slugOf(file)}.md`), `<!-- Generated by scripts/6_plans.mjs; edit ${source}. -->\n${body}`)
}
console.log(`plans: generated ${files.length} proposed-work pages`)
