import type { ExpressionIr, PipelineIr } from './0_pipelineIr'

function expressionCode(expression: ExpressionIr, parameter: string): string {
  if (expression.kind === 'parameter') return parameter
  if (expression.kind === 'literal') return String(expression.value)
  return `${expressionCode(expression.left, parameter)} ${expression.operator} ${expressionCode(expression.right, parameter)}`
}

export function generateRxjs(pipeline: PipelineIr) {
  const [mergeByKey, ...operators] = pipeline.pipe
  const inputs = Object.entries(pipeline.input.entries)
  const inputTypes = inputs.map(([, source]) => source.type.name)
  const switchMap = operators.find((operator) => operator.kind === 'switchMap')
  if (switchMap) {
    const types = [...new Set([mergeByKey.event.name, pipeline.output.name, ...inputTypes])].join(', ')
    const inputProperties = inputs.map(([key, source]) => `  ${key}: Observable<${source.type.name}>`).join('\n')
    const mergedInputs = inputs.map(([key, source]) => `    inputs.${key}.pipe(map((${mergeByKey.valueField}): ${mergeByKey.event.name} => ({ type: '${source.eventVariant}', ${mergeByKey.valueField} }))),`).join('\n')
    return `// @generated by @hafley66/json-rx
// DO NOT EDIT.

import { defer, finalize, map, merge, switchMap, timer, type Observable } from 'rxjs'
import type { ${types} } from './0_models'

export type ${pipeline.output.name}Metrics = { active: number; cancellations: number }

export function ${pipeline.name}(inputs: {
${inputProperties}
}, metrics: ${pipeline.output.name}Metrics): Observable<${pipeline.output.name}> {
  return merge(
${mergedInputs}
  ).pipe(
    switchMap((event) => defer(() => {
      metrics.active += 1
      let emitted = false
      return timer(event.${mergeByKey.valueField}.${switchMap.delayField}).pipe(
        map(() => {
          emitted = true
          return event.${mergeByKey.valueField}.${switchMap.outputField} as ${pipeline.output.name}
        }),
        finalize(() => {
          if (!emitted) metrics.cancellations += 1
          metrics.active -= 1
        }),
      )
    })),
  )
}
`
  }
  const scan = operators.find((operator) => operator.kind === 'scan')
  if (!scan) throw new Error(`Pipeline ${pipeline.name} requires scan`)
  const imports = [...new Set([
    'map',
    'merge',
    'scan',
    ...(operators.some((operator) => operator.kind === 'filter') ? ['filter'] : []),
    'type Observable',
  ])].join(', ')
  const types = [...new Set([mergeByKey.event.name, pipeline.output.name, ...inputTypes])].join(', ')
  const inputProperties = inputs.map(([key, source]) => `  ${key}: Observable<${source.type.name}>`).join('\n')
  const mergedInputs = inputs.map(([key, source]) => `    inputs.${key}.pipe(map((${mergeByKey.valueField}): ${mergeByKey.event.name} => ({ type: '${source.eventVariant}', ${mergeByKey.valueField} }))),`).join('\n')
  const operatorCode = operators.map((operator) => {
    if (operator.kind === 'map') return `    map((event: ${mergeByKey.event.name}) => ${expressionCode(operator.expression, `event.${mergeByKey.valueField}`)}),`
    if (operator.kind === 'filter') return `    filter((value) => ${expressionCode(operator.predicate, 'value')}),`
    if (operator.kind === 'switchMap') throw new Error(`Pipeline ${pipeline.name} switchMap must be its only operator`)
    const reducer = operator.reducer
    if (reducer.kind === 'sum') return `    scan((state: ${pipeline.output.name}, value) => state + value, ${expressionCode(reducer.seed, 'value')} as ${pipeline.output.name}),`
    const reducerCases = reducer.cases.map(({ variant, mode }) => `        case '${variant}':\n          return ${mode === 'replace' ? `event.${mergeByKey.valueField}` : `{ ...state, ...event.${mergeByKey.valueField} }`}`).join('\n')
    return `    scan((state: ${pipeline.output.name}, event: ${mergeByKey.event.name}) => {
      switch (event.type) {
${reducerCases}
      }
    }, {} as ${pipeline.output.name}),`
  }).join('\n')
  return `// @generated by @hafley66/json-rx
// DO NOT EDIT.

import { ${imports} } from 'rxjs'
import type { ${types} } from './0_models'

export function ${pipeline.name}(inputs: {
${inputProperties}
}): Observable<${pipeline.output.name}> {
  return merge(
${mergedInputs}
  ).pipe(
${operatorCode}
  )
}
`
}
