import type { ExpressionIr, PipelineIr } from './0_pipelineIr'

function snakeCase(value: string) {
  return value.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
}

function rustVariant(value: string) {
  return value[0].toUpperCase() + value.slice(1)
}

function expressionCode(expression: ExpressionIr, parameter: string): string {
  if (expression.kind === 'parameter') return parameter
  if (expression.kind === 'literal') return String(expression.value)
  return `${expressionCode(expression.left, parameter)} ${expression.operator} ${expressionCode(expression.right, parameter)}`
}

export function generateRust(pipeline: PipelineIr) {
  const [mergeByKey, ...operators] = pipeline.pipe
  const inputs = Object.entries(pipeline.input.entries)
  const functionName = snakeCase(pipeline.name)
  const generics = inputs.map((_, index) => `S${index}`).join(', ')
  const parameters = inputs.map(([key], index) => `mut ${key}: S${index}`).join(', ')
  const bounds = inputs.map(([, source], index) => `    S${index}: Stream<Item = ${source.type.name}> + Unpin,`).join('\n')
  const flags = inputs.map(([key]) => `        let mut ${key}_done = false;`).join('\n')
  const complete = inputs.map(([key]) => `${key}_done`).join(' && ')
  const branches = inputs.map(([key, source]) => `                item = ${key}.next(), if !${key}_done => match item {
                    Some(value) => ${mergeByKey.event.name}::${rustVariant(source.eventVariant)} { ${mergeByKey.valueField}: value },
                    None => { ${key}_done = true; continue; }
                },`).join('\n')
  const importedTypes = [...new Set([mergeByKey.event.name, pipeline.output.name, ...inputs.map(([, source]) => source.type.name)])].join(', ')
  const switchMap = operators.find((operator) => operator.kind === 'switchMap')
  if (switchMap) {
    if (inputs.length !== 1) throw new Error(`Pipeline ${pipeline.name} switchMap requires one input`)
    const [[inputKey, input]] = inputs
    const metrics = `${pipeline.output.name}Metrics`
    const activeTask = `${pipeline.output.name}ActiveTask`
    const switchMapTypes = [...new Set([pipeline.output.name, input.type.name, metrics])].join(', ')
    return `// @generated by @hafley66/json-rx
// DO NOT EDIT.

use async_stream::stream;
use futures::{future, Stream, StreamExt};
use std::{sync::{Arc, atomic::Ordering}, time::Duration};
use crate::models::{${switchMapTypes}};

struct ${activeTask}(Arc<${metrics}>);

impl Drop for ${activeTask} {
    fn drop(&mut self) {
        self.0.active.fetch_sub(1, Ordering::SeqCst);
    }
}

pub fn ${functionName}<S0>(mut ${inputKey}: S0, metrics: Arc<${metrics}>) -> impl Stream<Item = ${pipeline.output.name}>
where
    S0: Stream<Item = ${input.type.name}> + Unpin,
{
    stream! {
        let mut ${inputKey}_done = false;
        let mut active: Option<tokio::task::JoinHandle<${pipeline.output.name}>> = None;
        loop {
            if ${inputKey}_done && active.is_none() { break; }
            tokio::select! {
                item = ${inputKey}.next(), if !${inputKey}_done => match item {
                    Some(value) => {
                        if let Some(task) = active.take() {
                            metrics.cancellations.fetch_add(1, Ordering::SeqCst);
                            task.abort();
                            let _ = task.await;
                        }
                        let delay = value.${switchMap.delayField};
                        let output = value.${switchMap.outputField};
                        let task_metrics = metrics.clone();
                        active = Some(tokio::spawn(async move {
                            task_metrics.active.fetch_add(1, Ordering::SeqCst);
                            let _active = ${activeTask}(task_metrics);
                            tokio::time::sleep(Duration::from_millis(delay as u64)).await;
                            output
                        }));
                    }
                    None => ${inputKey}_done = true,
                },
                result = async {
                    match active.as_mut() {
                        Some(task) => task.await,
                        None => future::pending().await,
                    }
                }, if active.is_some() => {
                    active = None;
                    if let Ok(output) = result { yield output; }
                },
            }
        }
    }
}
`
  }
  const scan = operators.find((operator) => operator.kind === 'scan')
  if (!scan) throw new Error(`Pipeline ${pipeline.name} requires scan`)

  if (scan.reducer.kind === 'snapshotPatch') {
    const reducerCases = scan.reducer.cases.map(({ variant, mode }) => `                ${mergeByKey.event.name}::${rustVariant(variant)} { ${mergeByKey.valueField} } => ${mode === 'replace' ? `state = ${mergeByKey.valueField}` : `state.apply(${mergeByKey.valueField})`},`).join('\n')
    return `// @generated by @hafley66/json-rx
// DO NOT EDIT.

use async_stream::stream;
use futures::{Stream, StreamExt};
use crate::models::{${importedTypes}};

pub fn ${functionName}<${generics}>(${parameters}) -> impl Stream<Item = ${pipeline.output.name}>
where
${bounds}
{
    stream! {
        let mut state = ${pipeline.output.name}::default();
${flags}
        loop {
            if ${complete} { break; }
            let event = tokio::select! {
${branches}
            };
            match event {
${reducerCases}
            }
            yield state.clone();
        }
    }
}
`
  }

  const map = operators.find((operator) => operator.kind === 'map')
  const filter = operators.find((operator) => operator.kind === 'filter')
  if (!map || !filter || scan.reducer.kind !== 'sum') throw new Error(`Pipeline ${pipeline.name} requires map, filter, and sum scan`)
  const valueCases = inputs.map(([, source]) => `                ${mergeByKey.event.name}::${rustVariant(source.eventVariant)} { ${mergeByKey.valueField} } => ${expressionCode(map.expression, mergeByKey.valueField)},`).join('\n')
  return `// @generated by @hafley66/json-rx
// DO NOT EDIT.

use async_stream::stream;
use futures::{Stream, StreamExt};
use crate::models::{${importedTypes}};

pub fn ${functionName}<${generics}>(${parameters}) -> impl Stream<Item = ${pipeline.output.name}>
where
${bounds}
{
    stream! {
        let mut state = ${expressionCode(scan.reducer.seed, 'value')} as ${pipeline.output.name};
${flags}
        loop {
            if ${complete} { break; }
            let event = tokio::select! {
${branches}
            };
            let value = match event {
${valueCases}
            };
            if !(${expressionCode(filter.predicate, 'value')}) { continue; }
            state = state + value;
            yield state;
        }
    }
}
`
}
