import type { ReactiveStateIr } from './0_pipelineIr'

export function generateReactiveStateTs(ir: ReactiveStateIr) {
  const { name, next, failure } = ir
  return `// @generated by @hafley66/json-rx
// DO NOT EDIT.

import { Signal } from '@hafley66/signals'
import type { Observable } from 'rxjs'
import type { ${next.name}, ${failure.name} } from './0_models'

export type ${name} = { status: 'idle' | 'loading' | 'next' | 'error' | 'complete' | 'finalize'; data?: ${next.name}; error?: ${failure.name}; complete: boolean; loading: boolean; stale: boolean; updatedAt?: number; unsubscribed?: string }
export type ${name}Event = { kind: 'subscribe' } | { kind: 'loading' } | { kind: 'next'; data: ${next.name}; at: number } | { kind: 'error'; error: ${failure.name} } | { kind: 'complete' } | { kind: 'invalidate' } | { kind: 'unsubscribe'; reason: string } | { kind: 'finalize' }
export const initial${name}: ${name} = { status: 'idle', complete: false, loading: false, stale: false }
export function reduce${name}(state: ${name}, event: ${name}Event): ${name} {
  if (event.kind === 'subscribe') return { ...state, status: 'idle', complete: false, loading: false, unsubscribed: undefined }
  if (event.kind === 'loading') return { ...state, status: 'loading', loading: true }
  if (event.kind === 'next') return { ...state, status: 'next', data: event.data, error: undefined, loading: false, stale: false, updatedAt: event.at }
  if (event.kind === 'error') return { ...state, status: 'error', error: event.error, loading: false }
  if (event.kind === 'complete') return { ...state, status: 'complete', complete: true, loading: false }
  if (event.kind === 'invalidate') return { ...state, stale: true }
  if (event.kind === 'unsubscribe') return { ...state, loading: false, unsubscribed: event.reason }
  return { ...state, status: 'finalize', loading: false }
}
export function create${name}Signal(events: Observable<${name}Event>) {
  const state = Signal(initial${name})
  let active = 1
  const subscription = events.subscribe((event) => state.$(reduce${name}(state.$(), event)))
  return { state, metrics: { active: () => active }, dispose: () => { subscription.unsubscribe(); active = 0 } }
}
`
}

export function generateReactiveStateRust(ir: ReactiveStateIr) {
  const { name, next, failure } = ir
  return `// @generated by @hafley66/json-rx
// DO NOT EDIT.

use serde::{Deserialize, Serialize};
use futures_signals::signal::Mutable;
use std::sync::atomic::{AtomicUsize, Ordering};
use crate::models::{${next.name}, ${failure.name}};

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ${name} { pub status: ${name}Status, #[serde(skip_serializing_if = "Option::is_none")] pub data: Option<${next.name}>, #[serde(skip_serializing_if = "Option::is_none")] pub error: Option<${failure.name}>, pub complete: bool, pub loading: bool, pub stale: bool, #[serde(skip_serializing_if = "Option::is_none")] pub updated_at: Option<i64>, #[serde(skip_serializing_if = "Option::is_none")] pub unsubscribed: Option<String> }
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ${name}Status { Idle, Loading, Next, Error, Complete, Finalize }
#[derive(Clone, Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ${name}Event { Subscribe, Loading, Next { data: ${next.name}, at: i64 }, Error { error: ${failure.name} }, Complete, Invalidate, Unsubscribe { reason: String }, Finalize }
pub fn initial_${name.toLowerCase()}() -> ${name} { ${name} { status: ${name}Status::Idle, data: None, error: None, complete: false, loading: false, stale: false, updated_at: None, unsubscribed: None } }
pub fn reduce_${name.toLowerCase()}(mut state: ${name}, event: ${name}Event) -> ${name} { match event { ${name}Event::Subscribe => { state.status = ${name}Status::Idle; state.complete = false; state.loading = false; state.unsubscribed = None; }, ${name}Event::Loading => { state.status = ${name}Status::Loading; state.loading = true; }, ${name}Event::Next { data, at } => { state.status = ${name}Status::Next; state.data = Some(data); state.error = None; state.loading = false; state.stale = false; state.updated_at = Some(at); }, ${name}Event::Error { error } => { state.status = ${name}Status::Error; state.error = Some(error); state.loading = false; }, ${name}Event::Complete => { state.status = ${name}Status::Complete; state.complete = true; state.loading = false; }, ${name}Event::Invalidate => state.stale = true, ${name}Event::Unsubscribe { reason } => { state.loading = false; state.unsubscribed = Some(reason); }, ${name}Event::Finalize => { state.status = ${name}Status::Finalize; state.loading = false; } }; state }
pub struct ${name}Mutable { pub state: Mutable<${name}>, pub active: AtomicUsize }
impl ${name}Mutable { pub fn new() -> Self { Self { state: Mutable::new(initial_${name.toLowerCase()}()), active: AtomicUsize::new(1) } } pub fn apply(&self, event: ${name}Event) { self.state.set(reduce_${name.toLowerCase()}(self.state.get_cloned(), event)); } pub fn dispose(&self) { self.active.store(0, Ordering::SeqCst); } }
`
}
