export { vitestPlaywright } from "./1_plugin.js"
export type { VitestPlaywrightOptions, ResolvedOptions, ServeOptions } from "./0_options.js"
export { test, it, describe, expect } from "./4_test.js"
export type { PwWorker, PwFile, PwTest } from "./4_test.js"
export { playwrightMatchers, serializeExpectedText } from "./3_matchers.js"
export type { PlaywrightMatchers } from "./3_matchers.js"
export { acquire, resource$, browser$, context$, page$, request$, pageEvents$, attemptEvents$, nodeFetch$, apiCall$, poll$, sleep$, real } from "./5_streams.js"
export type { Resource, Handle } from "./5_streams.js"
export { als, active, taskRoots } from "./6_roots.js"
export type { TestRoot, TestLog, TestLogState, NetEvent, AttemptEvent, ApiEvent } from "./6_roots.js"
export type { PageGlobals } from "./7_page-global.js"
