import type { AnySpec, Presets, ValuesOf } from "@hafley66/report-shell"
import { CURVES, FLY, GAPS } from "../../lib/6_slice.js"
import { PLAYBACK_INPUTS, PLAYBACK_PRESETS, SEED_INPUTS, STROKE_INPUTS, STROKE_PRESETS } from "../0_inputs.js"

export const SLICE_REVEAL_INPUTS = {
  reveal: {
    kind: "select",
    hint: "how a stroke appears: drawn along its length, cut in behind a riding blade, slid along its own chord, both, or glowed up",
    options: ["draw", "cut", "slide", "draw+slide", "glow"],
    default: "draw",
    pool: ["draw", "cut", "cut", "slide", "draw+slide", "glow"],
  },
} as const satisfies AnySpec

export const SLICE_CUT_INPUTS = {
  cut: {
    kind: "range",
    hint: "stroke length in px: every subpath is cut into equal arc-length pieces",
    min: 8,
    max: 160,
    default: 48,
    label: "cut px",
    roll: [12, 92],
    group: "cut",
  },
  angle: {
    kind: "range",
    hint: "sweep direction in degrees; orders the sweep only, each stroke still flies along its own chord",
    min: 0,
    max: 360,
    default: 215,
    group: "cut",
  },
  jit: {
    kind: "range",
    hint: "random spread added to the sweep angle per stroke, in degrees",
    min: 0,
    max: 180,
    default: 18,
    label: "jitter",
    roll: [0, 40],
    group: "cut",
  },
  dist: {
    kind: "range",
    hint: "flight distance in chord lengths",
    min: 0.3,
    max: 3,
    step: 0.1,
    default: 1.2,
    roll: [0.5, 2.5],
    group: "cut",
  },
  flight: {
    kind: "range",
    hint: "flight time per stroke in ms",
    min: 60,
    max: 600,
    step: 10,
    default: 160,
    roll: [80, 320],
    group: "cut",
  },
} as const satisfies AnySpec

export const SLICE_ORDER_INPUTS = {
  order: {
    kind: "select",
    hint: "which stroke starts when: geometric sweeps, path order, golden / van der Corput / spectral / hilbert low-discrepancy orders, or random",
    options: [
      "sweep",
      "radial",
      "radial-in",
      "path",
      "subpath",
      "golden",
      "golden-angle",
      "vdc",
      "spectral",
      "hilbert",
      "random",
    ],
    default: "sweep",
    pool: [
      "sweep",
      "radial",
      "radial-in",
      "path",
      "subpath",
      "golden",
      "golden",
      "golden-angle",
      "vdc",
      "spectral",
      "spectral",
      "hilbert",
    ],
    group: "order",
  },
  curve: {
    kind: "select",
    hint: "start-time progression: shaped curves, or stochastic gap generators (poisson, gamma, levy, colored noise)",
    options: [...Object.keys(CURVES), ...Object.keys(GAPS)],
    default: "linear",
    group: "order",
  },
  ordN: {
    kind: "range",
    hint: "the curve's parameter: smooth-N power, fourier beta, gamma or levy k",
    min: 1,
    max: 8,
    step: 0.5,
    default: 2,
    label: "N/β/k",
    roll: [1, 6],
    group: "order",
  },
  gain: {
    kind: "range",
    hint: "contrast of the progression curve; 0 = linear",
    min: 0,
    max: 4,
    step: 0.1,
    default: 1.5,
    roll: [0.3, 3],
    group: "order",
  },
  silence: {
    kind: "range",
    hint: "clamps every gap to this many medians, so the cycle has no dead air",
    min: 1,
    max: 8,
    step: 0.5,
    default: 2.5,
    roll: [1.5, 5],
    group: "order",
  },
  spread: {
    kind: "range",
    hint: "total start-time window across all strokes, in ms",
    min: 0,
    max: 3000,
    step: 50,
    default: 800,
    roll: [200, 1600],
    group: "order",
  },
  burst: {
    kind: "range",
    hint: "steps the window is quantised into; 1 = all at once, 16 = fine",
    min: 1,
    max: 16,
    default: 10,
    label: "steps",
    roll: [1, 15],
    group: "order",
  },
} as const satisfies AnySpec

export const SLICE_FLIGHT_INPUTS = {
  fease: {
    kind: "select",
    hint: "easing of the fly-in; spring uses anime.js Spring",
    options: Object.keys(FLY),
    default: "back",
    label: "fly ease",
    group: "fly",
  },
  stretch: {
    kind: "range",
    hint: "stroke stretched along its flight direction at launch",
    min: 0,
    max: 2.5,
    step: 0.05,
    default: 0.9,
    roll: [0, 2.2],
    group: "fly",
  },
  os: {
    kind: "range",
    hint: "overshoot past the resting place before settling",
    min: 0,
    max: 1.4,
    step: 0.05,
    default: 0.5,
    label: "overshoot",
    roll: [0, 1.2],
    group: "fly",
  },
  ailen: {
    kind: "range",
    hint: "afterimage length in stroke lengths",
    min: 0.5,
    max: 5,
    step: 0.1,
    default: 2,
    label: "ai len",
    roll: [0.5, 4],
    group: "fly",
  },
  ai: {
    kind: "bool",
    hint: "leave a fading afterimage behind each stroke",
    default: true,
    label: "afterimage",
  },
  aiOpacity: { kind: "range", min: 0, max: 1, step: 0.01, default: 0.85, label: "ai opacity", hint: "afterimage peak opacity; its settings can vary independently per stroke", group: "fly" },
  aiFade: { kind: "range", min: 20, max: 2000, step: 10, default: 120, label: "ai fade ms", hint: "afterimage lifetime after landing in milliseconds; its settings can vary independently per stroke", group: "fly" },
} as const satisfies AnySpec

export const SLICE_SPEC = {
  seed: { ...SEED_INPUTS.seed, hint: "seed for the seal and every stochastic order and gap" },
  ...SLICE_REVEAL_INPUTS,
  ...SLICE_CUT_INPUTS,
  ...SLICE_ORDER_INPUTS,
  ...SLICE_FLIGHT_INPUTS,
  ...STROKE_INPUTS,
  weight: { ...STROKE_INPUTS.weight, label: "slice weight", hint: "width multiplier for moving strokes, blades and afterimages" },
  finalWeight: { ...STROKE_INPUTS.weight, label: "path weight", hint: "width multiplier for the completed paths" },
  ...PLAYBACK_INPUTS,
  time: { ...PLAYBACK_INPUTS.time, default: 0 },
  speed: { ...PLAYBACK_INPUTS.speed, default: 1 },
} as const satisfies AnySpec
export type SliceParams = ValuesOf<typeof SLICE_SPEC>

export const SLICE_DEFAULTS = Object.fromEntries(Object.entries(SLICE_SPEC).map(([key, field]) => [key, field.default])) as SliceParams

export const SLICE_PRESETS = {
  "ink · sweep": { reveal: "draw", order: "sweep", curve: "linear", spread: 800, flight: 160, burst: 10, ai: true },
  "blade · radial": { reveal: "cut", order: "radial", curve: "linear", spread: 1200, flight: 240, burst: 12, ai: true },
  "ribbon · flight": { reveal: "draw+slide", order: "path", curve: "linear", spread: 1600, flight: 320, burst: 16, dist: 2, stretch: 1.5, ai: true },
  "light · scattered": { reveal: "glow", order: "random", curve: "linear", spread: 1000, flight: 400, burst: 16, ai: false },
  ...STROKE_PRESETS,
  ...PLAYBACK_PRESETS,
} as const satisfies Presets<SliceParams>
