// @generated by @hafley66/json-rx
// DO NOT EDIT.

use serde::{Deserialize, Serialize};
use futures_signals::signal::Mutable;
use std::sync::atomic::{AtomicUsize, Ordering};
use crate::models::{Value, Failure};

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct LifecycleState { pub status: LifecycleStateStatus, #[serde(skip_serializing_if = "Option::is_none")] pub data: Option<Value>, #[serde(skip_serializing_if = "Option::is_none")] pub error: Option<Failure>, pub complete: bool, pub loading: bool, pub stale: bool, #[serde(skip_serializing_if = "Option::is_none")] pub updated_at: Option<i64>, #[serde(skip_serializing_if = "Option::is_none")] pub unsubscribed: Option<String> }
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum LifecycleStateStatus { Idle, Loading, Next, Error, Complete, Finalize }
#[derive(Clone, Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum LifecycleStateEvent { Subscribe, Loading, Next { data: Value, at: i64 }, Error { error: Failure }, Complete, Invalidate, Unsubscribe { reason: String }, Finalize }
pub fn initial_lifecyclestate() -> LifecycleState { LifecycleState { status: LifecycleStateStatus::Idle, data: None, error: None, complete: false, loading: false, stale: false, updated_at: None, unsubscribed: None } }
pub fn reduce_lifecyclestate(mut state: LifecycleState, event: LifecycleStateEvent) -> LifecycleState { match event { LifecycleStateEvent::Subscribe => { state.status = LifecycleStateStatus::Idle; state.complete = false; state.loading = false; state.unsubscribed = None; }, LifecycleStateEvent::Loading => { state.status = LifecycleStateStatus::Loading; state.loading = true; }, LifecycleStateEvent::Next { data, at } => { state.status = LifecycleStateStatus::Next; state.data = Some(data); state.error = None; state.loading = false; state.stale = false; state.updated_at = Some(at); }, LifecycleStateEvent::Error { error } => { state.status = LifecycleStateStatus::Error; state.error = Some(error); state.loading = false; }, LifecycleStateEvent::Complete => { state.status = LifecycleStateStatus::Complete; state.complete = true; state.loading = false; }, LifecycleStateEvent::Invalidate => state.stale = true, LifecycleStateEvent::Unsubscribe { reason } => { state.loading = false; state.unsubscribed = Some(reason); }, LifecycleStateEvent::Finalize => { state.status = LifecycleStateStatus::Finalize; state.loading = false; } }; state }
pub struct LifecycleStateMutable { pub state: Mutable<LifecycleState>, pub active: AtomicUsize }
impl LifecycleStateMutable { pub fn new() -> Self { Self { state: Mutable::new(initial_lifecyclestate()), active: AtomicUsize::new(1) } } pub fn apply(&self, event: LifecycleStateEvent) { self.state.set(reduce_lifecyclestate(self.state.get_cloned(), event)); } pub fn dispose(&self) { self.active.store(0, Ordering::SeqCst); } }
