// @generated by @hafley66/json-rx
// DO NOT EDIT.

use async_stream::stream;
use futures::{Stream, StreamExt};
use crate::models::{UsageEvent, UsageSnapshot, UsageUpdate};

pub fn usage_state<S0, S1>(mut snapshot: S0, mut update: S1) -> impl Stream<Item = UsageSnapshot>
where
    S0: Stream<Item = UsageSnapshot> + Unpin,
    S1: Stream<Item = UsageUpdate> + Unpin,
{
    stream! {
        let mut state = UsageSnapshot::default();
        let mut snapshot_done = false;
        let mut update_done = false;
        loop {
            if snapshot_done && update_done { break; }
            let event = tokio::select! {
                item = snapshot.next(), if !snapshot_done => match item {
                    Some(value) => UsageEvent::Snapshot { value: value },
                    None => { snapshot_done = true; continue; }
                },
                item = update.next(), if !update_done => match item {
                    Some(value) => UsageEvent::Update { value: value },
                    None => { update_done = true; continue; }
                },
            };
            match event {
                UsageEvent::Snapshot { value } => state = value,
                UsageEvent::Update { value } => state.apply(value),
            }
            yield state.clone();
        }
    }
}
