import { compile, NodeHost } from '@typespec/compiler'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { AutomationJsonSchema } from '../src/1_schema'
import { generateAutomation } from '../src/4_typespec/3_emitter'

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const automations = [
  {
    source: 'src/5_automations/0_claude_usage/0_input.tsp',
    output: 'src/5_automations/0_claude_usage/1_document.auto.ts',
    snapshot: 'src/5_automations/0_claude_usage/2_document.snapshot.json',
    exportName: 'claudeUsage',
  },
  {
    source: 'src/5_automations/1_logic/0_input.tsp',
    output: 'src/5_automations/1_logic/1_document.auto.ts',
    snapshot: 'src/5_automations/1_logic/2_document.snapshot.json',
    exportName: 'logic',
  },
]
const files = new Map<string, string>([
  ['automation.schema.json', `${JSON.stringify(AutomationJsonSchema, null, 2)}\n`],
])
for (const automation of automations) {
  const program = await compile(NodeHost, resolve(packageDir, automation.source), { noEmit: true })
  const errors = program.diagnostics.filter((diagnostic) => diagnostic.severity === 'error')
  if (errors.length > 0) throw new Error(errors.map((diagnostic) => diagnostic.message).join('\n'))
  const { document, catalog } = generateAutomation(program)
  const generatedHeader = `// @generated by @hafley66/json-rx\n// Source: ${automation.source}\n// DO NOT EDIT. Run: pnpm generate\n\n`
  const documentModule = `${generatedHeader}import type { Automation } from '../../1_schema'\n\nexport const ${automation.exportName}Automation = ${JSON.stringify(document, null, 2)} as const satisfies Automation\n\nexport const ${automation.exportName}Catalog = ${JSON.stringify(catalog, null, 2)} as const\n`
  files.set(automation.output, documentModule)
  files.set(automation.snapshot, `${JSON.stringify(document, null, 2)}\n`)
}
const check = process.argv.includes('--check')
const stale: string[] = []
for (const [path, contents] of files) {
  const target = resolve(packageDir, path)
  await mkdir(dirname(target), { recursive: true })
  const previous = await readFile(target, 'utf8').catch(() => '')
  if (previous === contents) continue
  if (check) stale.push(path)
  else await writeFile(target, contents)
}
if (stale.length > 0) throw new Error(`Generated files are stale:\n${stale.join('\n')}`)
