import { compile, NodeHost } from '@typespec/compiler'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { AutomationJsonSchema } from '../src/1_schema'
import { generateAutomation } from '../src/4_typespec/3_emitter'

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = 'src/5_automations/0_claude_usage/0_input.tsp'
const program = await compile(NodeHost, resolve(packageDir, source), { noEmit: true })
const errors = program.diagnostics.filter((diagnostic) => diagnostic.severity === 'error')
if (errors.length > 0) {
  throw new Error(errors.map((diagnostic) => diagnostic.message).join('\n'))
}

const { document, catalog } = generateAutomation(program)
const generatedHeader = `// @generated by @hafley66/json-rx\n// Source: ${source}\n// DO NOT EDIT. Run: pnpm generate\n\n`
const documentModule = `${generatedHeader}import type { Automation } from '../../1_schema'\n\nexport const claudeUsageAutomation = ${JSON.stringify(document, null, 2)} as const satisfies Automation\n\nexport const claudeUsageCatalog = ${JSON.stringify(catalog, null, 2)} as const\n`
const files = new Map([
  ['automation.schema.json', `${JSON.stringify(AutomationJsonSchema, null, 2)}\n`],
  ['src/5_automations/0_claude_usage/1_document.auto.ts', documentModule],
  ['src/5_automations/0_claude_usage/2_document.snapshot.json', `${JSON.stringify(document, null, 2)}\n`],
])
const check = process.argv.includes('--check')
const stale: string[] = []
for (const [path, contents] of files) {
  const target = resolve(packageDir, path)
  await mkdir(dirname(target), { recursive: true })
  const previous = await readFile(target, 'utf8').catch(() => '')
  if (previous === contents) continue
  if (check) stale.push(path)
  else await writeFile(target, contents)
}
if (stale.length > 0) throw new Error(`Generated files are stale:\n${stale.join('\n')}`)
