import { readdir, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '../src')
const files = []
async function visit(directory) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name)
    if (entry.isDirectory()) await visit(path)
    else if (entry.name.endsWith('.auto.ts')) files.push(path)
  }
}
await visit(root)
const invalid = []
for (const path of files) {
  const contents = await readFile(path, 'utf8')
  if (!contents.startsWith('// @generated by @hafley66/json-rx\n')) invalid.push(path)
}
if (invalid.length > 0) throw new Error(`Generated headers missing:\n${invalid.join('\n')}`)
