import { svgInferFrame, type SvgInferResult, type SvgInferStep } from "../../../src/2_graph/24_svgInfer.ts"
import largeFixture from "../../../fixtures/sequence/large.json"
import largeSvgUrl from "../../../fixtures/sequence/large.svg?url"
import d2Fixture from "../../../fixtures/sequence/paired-d2.json"
import d2SvgUrl from "../../../fixtures/sequence/paired-d2.svg?url"
import mermaidFixture from "../../../fixtures/sequence/paired-mermaid.json"
import mermaidSvgUrl from "../../../fixtures/sequence/paired-mermaid.svg?url"

export type SvgInferExample = "sequence-svg" | "paired-d2-svg" | "paired-mermaid-svg"

type Reference = {
  source?: string
  graph: Record<string, { type: string; fromId?: string; toId?: string; data?: { label?: string } }>
  bindings: { elementId: string; graphId: string; role: string }[]
}

export type SvgInferReport = {
  referenceEdges: number
  inferredEdges: number
  matched: string[]
  missed: string[]
  extra: string[]
  unanchored: string[]
}

/** Fixtures are generated by scripts/3_generate_sequence_fixture.mjs; check presence here, trust the generator for shape. */
function referenceOf(fixture: unknown, locator: string): Reference {
  if (typeof fixture !== "object" || fixture === null) throw new Error(`${locator}: fixture is not an object`)
  const record = fixture as Record<string, unknown>
  if (typeof record.graph !== "object" || record.graph === null) throw new Error(`${locator}: fixture has no graph`)
  if (!Array.isArray(record.bindings)) throw new Error(`${locator}: fixture has no bindings`)
  return {
    graph: record.graph as Reference["graph"],
    bindings: record.bindings as Reference["bindings"],
    source: typeof record.source === "string" ? record.source : undefined,
  }
}

const fixtures: Record<SvgInferExample, { url: string; reference: Reference }> = {
  "sequence-svg": { url: largeSvgUrl, reference: referenceOf(largeFixture, "large.json") },
  "paired-d2-svg": { url: d2SvgUrl, reference: referenceOf(d2Fixture, "paired-d2.json") },
  "paired-mermaid-svg": { url: mermaidSvgUrl, reference: referenceOf(mermaidFixture, "paired-mermaid.json") },
}

/** The fixture carries the authored relations and the element each occurrence bound to, so an
 * SVG-only parse can be scored against the explicit reference instead of eyeballed. */
export function compareSvgInference(reference: Reference, steps: readonly SvgInferStep[]): SvgInferReport {
  const occurrenceByElementId = new Map(reference.bindings.map(binding => [binding.elementId, binding.graphId]))
  const referenceEdges = new Set(
    Object.values(reference.graph)
      .filter(item => item.type === "edge")
      .map(item => `${item.fromId} -> ${item.toId}`),
  )
  const inferredEdges = new Set(
    steps.flatMap(step =>
      step.kind === "edge"
        ? [`${occurrenceByElementId.get(step.fromId) ?? step.fromId} -> ${occurrenceByElementId.get(step.toId) ?? step.toId}`]
        : [],
    ),
  )
  return {
    referenceEdges: referenceEdges.size,
    inferredEdges: inferredEdges.size,
    matched: [...inferredEdges].filter(edge => referenceEdges.has(edge)).sort(),
    missed: [...referenceEdges].filter(edge => !inferredEdges.has(edge)).sort(),
    extra: [...inferredEdges].filter(edge => !referenceEdges.has(edge)).sort(),
    unanchored: steps.flatMap(step => (step.kind === "lost" ? [step.graphId] : [])),
  }
}

export async function svgInferSequence(
  viewport: { width: number; height: number },
  example: SvgInferExample,
  onStep?: (step: SvgInferStep) => void,
): Promise<SvgInferResult & { report: SvgInferReport }> {
  const fixture = fixtures[example]
  const svg = await (await fetch(fixture.url)).text()
  const result = svgInferFrame(document, { svg, locator: fixture.reference.source ?? example, rootId: "seq", viewport, onStep })
  return { ...result, report: compareSvgInference(fixture.reference, result.steps) }
}

const short = (value: string, width = 52) => (value.length > width ? `${value.slice(0, width - 1)}…` : value)

/** One scan line per step, so the panel reads as the algorithm's transcript. */
export function formatSvgInferStep(source: string, step: SvgInferStep): string {
  switch (step.kind) {
    case "classify":
      return `${source}  classify ${step.role.padEnd(9)} ${step.elementId}  (${step.why})`
    case "label":
      return `${source}  label    ${step.graphId}  "${step.text}"`
    case "anchor":
      return `${source}  anchor   ${step.graphId}  ${step.end} -> ${step.hit ?? "none"}${Number.isFinite(step.distance) ? ` (gap ${step.distance.toFixed(1)})` : ""}${step.via === undefined ? "" : ` via ${step.via}`}`
    case "edge":
      return `${source}  edge     ${step.graphId}  ${step.fromId} -> ${step.toId} [${step.direction}]`
    case "lost":
      return `${source}  lost     ${step.graphId}  (${step.reason})`
  }
}

/** Reads the score against the reference; missed and extra rows are the interesting ones. */
export function describeSvgInference(result: SvgInferResult & { report: SvgInferReport }): string {
  const { counts, report } = result
  const lines = [
    `primitives ${counts.primitives} | areas ${counts.areas} | connectors ${counts.connectors} | edges ${counts.edges} | unanchored ${counts.lost}`,
    `reference ${report.referenceEdges} edges | inferred ${report.inferredEdges} | matched ${report.matched.length} | missed ${report.missed.length} | extra ${report.extra.length}`,
  ]
  for (const edge of report.missed) lines.push(`  missed  ${short(edge)}`)
  for (const edge of report.extra) lines.push(`  extra   ${short(edge)}`)
  for (const id of report.unanchored) lines.push(`  unanchored  ${short(id)}`)
  return lines.join("\n")
}
