// Exercise the shipped chunks: a development-server import can hide UMD/global collisions.
import { chromium, expect } from "@playwright/test"
import { preview } from "vite"
import { fileURLToPath } from "node:url"

const base = "/hafley-rxjs/grapht/proof/"
const server = process.argv[2] ? undefined : await preview({
  configFile: false,
  base,
  build: { outDir: fileURLToPath(new URL("../../../site/dist/proof", import.meta.url)) },
  preview: { host: "127.0.0.1", port: 0, open: false },
})
let browser
try {
  browser = await chromium.launch()
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } })
  const errors = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto(process.argv[2] ?? server.resolvedUrls.local[0])
  await expect(page.locator("#host svg").first()).toBeVisible()
  await expect(page.locator('[data-performance-readout]')).toHaveCount(1)
  await expect(page.locator('[data-metric="fps"]')).toHaveText(/^\d+$/)
  await expect(page.locator('[data-metric="used"]')).toHaveText(/^(\d+\.\d MiB|unavailable)$/)
  await page.locator("#arch").click()
  await expect(page.locator("#renderer-cytoscape")).toBeDisabled()
  await expect(page.locator("#host canvas")).toHaveCount(0)
  for (const source of ["sequence", "sequence"]) {
    const rootId = source === "arch" ? "epic" : "seq"
    await page.locator(`#${source}`).click()
    const ribbon = page.locator("[data-sticky-ribbon] [data-sticky-id]")
    const groups = page.locator("[data-sticky-groups] [data-sticky-id]")
    if (source === "sequence") await expect(ribbon).toHaveCount(16)
    const documentNodes = await page.locator("#host *").count()
    const expectedHeaders = (await page.locator("[data-sticky-id] text").allTextContents()).sort()
    await page.getByRole("button", { name: "cytoscape renderer", exact: true }).click()
    await expect(page.locator('#readout')).toContainText(`${source} | cytoscape`)
    // Wait for the lazy import and render, including failures caught by the page itself.
    await expect.poll(async () => ({
      failed: (await page.locator('#readout').textContent()).includes("failed"),
      canvas: await page.locator('#host canvas').count() > 0,
      svg: await page.locator(`#host [data-revision-id] svg`).count() > 0,
    })).toEqual({ failed: false, canvas: true, svg: false })
    await expect.poll(async () => (await page.locator("[data-sticky-id] text").allTextContents()).sort()).toEqual(expectedHeaders)
    if (source === "sequence") {
      const groupCount = await groups.count()
      expect(groupCount).toBeGreaterThan(0)
      await page.locator("#ribbon").uncheck()
      await expect(ribbon).toHaveCount(0)
      await page.locator("#groups").uncheck()
      await expect(groups).toHaveCount(0)
      await page.locator("#ribbon").check()
      await page.locator("#groups").check()
      await expect(ribbon).toHaveCount(16)
      await expect(groups).toHaveCount(groupCount)
    }
    await expect(page.locator("#host")).toHaveAttribute("data-grapht-native-edge-count", "125")
    const nativeNodes = await page.locator("#host *").count()
    expect(nativeNodes).toBeLessThan(documentNodes / 2)
    const camera = async () => {
      const value = await page.locator("#readout").textContent()
      const match = /camera x (-?[\d.]+) y (-?[\d.]+) scale ([\d.]+)/.exec(value)
      return { x: Number(match[1]), y: Number(match[2]), scale: Number(match[3]) }
    }
    const before = await camera()
    await expect(page.locator("#dark")).toBeEnabled()
    await expect(page.locator("#dark")).toBeChecked()
    await expect(page.locator("#host")).toHaveCSS("background-color", "rgb(11, 18, 32)")
    await page.locator("#dark").uncheck()
    await expect(page.locator("#host")).toHaveCSS("background-color", "rgb(253, 253, 251)")
    await page.locator("#dark").check()
    await expect(page.locator("#host")).toHaveCSS("background-color", "rgb(11, 18, 32)")
    expect(await camera()).toEqual(before)
    await page.mouse.move(640, 400)
    await page.mouse.wheel(0, 100)
    await expect.poll(async () => (await camera()).y).toBeLessThan(before.y - 100)
    expect((await camera()).scale).toBe(before.scale)
    await page.keyboard.down("Control")
    await page.mouse.wheel(0, -100)
    await page.keyboard.up("Control")
    await expect.poll(async () => (await camera()).scale).toBeGreaterThan(before.scale)
    await page.getByRole("button", { name: "fit", exact: true }).click()
    await expect.poll(camera).toEqual(before)
    // Fit must cancel the entire half-second tail, including pending animation frames.
    await page.waitForTimeout(550)
    expect(await camera()).toEqual(before)
    if (process.env.SCREENSHOT) await page.screenshot({ path: process.env.SCREENSHOT })
    console.log(`Native sequence: DOM ${documentNodes} -> ${nativeNodes}`)
    await page.getByRole("button", { name: "document renderer", exact: true }).click()
    await expect(page.locator('#host canvas')).toHaveCount(0)
    await expect(page.locator("#host svg").first()).toBeVisible()
    await expect(page.locator("#dark")).toBeEnabled()
    await expect(page.locator("#host")).toHaveCSS("background-color", "rgb(11, 18, 32)")
    const domBefore = await camera()
    await page.mouse.move(640, 400)
    await page.mouse.wheel(0, 100)
    await expect.poll(async () => (await camera()).y).toBeLessThan(domBefore.y - 100)
    expect((await camera()).scale).toBe(domBefore.scale)
    await page.getByRole("button", { name: "fit", exact: true }).click()
    await expect.poll(camera).toEqual(domBefore)
    if (process.env.DOM_SCREENSHOT) await page.screenshot({ path: process.env.DOM_SCREENSHOT })
  }
  await page.locator("#interaction-controls > summary").click()
  await page.locator("#hover-debug").check()
  const hit = page.locator('#host [data-graph-id]').filter({ hasNot: page.locator('tspan') }).first()
  const hitId = await hit.getAttribute("data-graph-id")
  await hit.hover({ force: true })
  await expect(page.locator("#hover-inspector")).toContainText(hitId)
  await expect(page.locator("#hover-inspector")).toContainText('"bindings"')
  if (process.env.HOVER_SCREENSHOT) await page.screenshot({ path: process.env.HOVER_SCREENSHOT })
  await page.locator("#hover-mode").selectOption("upstream")
  await page.locator("#hover-relations").selectOption("sequence")
  await page.locator("#hover-depth").fill("3")
  await page.locator("#hover-depth").dispatchEvent("change")
  await page.locator("#source-text").click()
  await expect(page.locator("#source-preview")).toContainText("sequenceDiagram")
  await page.locator("#source-text").click()
  const collapse = page.locator("[data-collapse-id]").first()
  await collapse.check()
  await expect.poll(() => page.locator('#host [data-graph-id]').evaluateAll(elements => elements.filter(element => element.style.display === "none").length)).toBeGreaterThan(0)
  if (process.env.COLLAPSE_SCREENSHOT) await page.screenshot({ path: process.env.COLLAPSE_SCREENSHOT })
  await collapse.uncheck()
  await expect.poll(() => page.locator('#host [data-graph-id]').evaluateAll(elements => elements.filter(element => element.style.display === "none").length)).toBe(0)
  await page.getByText("Group actors", { exact: true }).click()
  const actorIds = await page.locator("#actor-members option").evaluateAll(options => options.slice(0, 2).map(option => option.value))
  await page.locator("#actor-members").selectOption(actorIds)
  await page.locator("#actor-group-name").fill("Services")
  await page.locator("#group-actors").click()
  await expect(page.locator("#collapse-controls")).toContainText("Collapse Services")
  await page.locator('[data-collapse-id="view-actor-group:1"]').check()
  await expect(page.locator("[data-sticky-ribbon] [data-sticky-id]")).toHaveCount(14)
  await page.locator("#renderer-cytoscape").click()
  await expect(page.locator("#host canvas")).not.toHaveCount(0)
  await expect(page.locator("[data-sticky-ribbon] [data-sticky-id]")).toHaveCount(14)
  await page.locator('[data-collapse-id="view-actor-group:1"]').uncheck()
  await expect(page.locator("[data-sticky-ribbon] [data-sticky-id]")).toHaveCount(16)
  await page.locator("#interaction-controls > summary").click()
  await page.locator("#layout-lab").click()
  const lab = page.locator("[data-layout-lab]")
  await expect(lab.locator("[data-policy]")).toHaveText("A: automatic · B: automatic")
  const bounds = await lab.locator("[data-canvas]").boundingBox()
  await page.mouse.move(bounds.x + 85, bounds.y + 97.5)
  await page.mouse.down()
  await page.mouse.move(bounds.x + 115, bounds.y + 117.5, { steps: 8 })
  await page.mouse.up()
  await expect(lab.locator("[data-policy]")).toHaveText("A: manual · B: automatic")
  await lab.locator('[data-collapse="a"]').click()
  await expect(lab.locator("[data-policy]")).toHaveText("A: collapsed · B: automatic")
  await lab.locator('[data-collapse="a"]').click()
  await expect(lab.locator("[data-policy]")).toHaveText("A: manual · B: automatic")
  await lab.locator("[data-auto-expand]").check()
  await lab.locator('[data-collapse="a"]').click()
  await lab.locator('[data-collapse="a"]').click()
  await expect(lab.locator("[data-policy]")).toHaveText("A: automatic · B: automatic")
  await lab.locator("[data-auto-expand]").uncheck()
  await lab.locator('[data-collapse="a"]').click()
  await lab.locator('[data-collapse="a"]').click()
  await expect(lab.locator("[data-policy]")).toHaveText("A: manual · B: automatic")
  if (process.env.LAB_SCREENSHOT) await page.screenshot({ path: process.env.LAB_SCREENSHOT })
  await lab.locator("[data-close]").click()
  expect(errors).toEqual([])
  console.log("Production proof passed: shared DOM/native themes, wheel momentum, native sequence, hover/debug modes, actor grouping, sequence collapse, and group layout expansion toggle.")
} finally {
  await browser?.close()
  await new Promise((resolve, reject) => server ? server.httpServer.close(error => error ? reject(error) : resolve()) : resolve())
}
