// @generated by @hafley66/json-rx
// Source: src/5_automations/0_claude_usage/0_input.tsp
// DO NOT EDIT. Run: pnpm generate

import type { Automation } from '../../1_schema'

export const claudeUsageAutomation = {
  "$schema": "./node_modules/@hafley66/json-rx/automation.schema.json",
  "version": "automation.v1",
  "profile": "rxjs-7.8",
  "id": "claude.usage",
  "enabled": true,
  "bindings": {
    "sources": {
      "claude.responses": {
        "kind": "http.event",
        "page": {
          "host": "claude.ai"
        },
        "request": {
          "methods": [
            "GET"
          ],
          "url": "/api/organizations/*/usage"
        }
      }
    }
  },
  "circuit": {
    "sources": {
      "claude.responses": {}
    },
    "reducers": {},
    "flows": {
      "usage": {
        "pipe": [
          {
            "node": "usage.source",
            "source": {
              "$ref": "claude.responses"
            }
          },
          {
            "node": "usage.map",
            "map": {
              "from": "$.body",
              "language": "jsonata",
              "fields": {
                "fiveHour": "five_hour.utilization",
                "sevenDay": "seven_day.utilization"
              }
            }
          },
          {
            "node": "usage.share",
            "shareReplay": {
              "bufferSize": 1,
              "refCount": true
            }
          }
        ]
      }
    }
  },
  "outputs": [
    {
      "kind": "host.emit",
      "flow": "usage",
      "stream": "claude.usage",
      "schema": {
        "type": "object",
        "additionalProperties": true
      }
    }
  ]
} as const satisfies Automation

export const claudeUsageCatalog = {
  "sources": [
    "claude.responses"
  ],
  "flows": [
    "usage"
  ]
} as const
